"""updated id field

Revision ID: 7b2fb6b0dc54
Revises: 8ff4022bf73f
Create Date: 2024-11-26 15:47:54.529399

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b2fb6b0dc54'
down_revision: Union[str, None] = '8ff4022bf73f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recycle', sa.Column('id', sa.UUID(), nullable=False))
    op.drop_index('ix_recycle_iid', table_name='recycle')
    op.create_index(op.f('ix_recycle_id'), 'recycle', ['id'], unique=False)
    op.drop_column('recycle', 'iid')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recycle', sa.Column('iid', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_recycle_id'), table_name='recycle')
    op.create_index('ix_recycle_iid', 'recycle', ['iid'], unique=False)
    op.drop_column('recycle', 'id')
    # ### end Alembic commands ###
