"""updated waste in db model

Revision ID: 8b012d3e70b2
Revises: 6fa5151d1299
Create Date: 2024-11-15 17:08:34.233181

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b012d3e70b2'
down_revision: Union[str, None] = '6fa5151d1299'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
