"""Made updated_at nullable

Revision ID: bcad5b7777bf
Revises: 4fbd01d5cc85
Create Date: 2024-11-15 17:02:13.861240

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bcad5b7777bf'
down_revision: Union[str, None] = '4fbd01d5cc85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
