"""Updated waste type code field

Revision ID: 4fbd01d5cc85
Revises: ef2e1a2bd772
Create Date: 2024-11-15 13:58:24.840473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4fbd01d5cc85'
down_revision: Union[str, None] = 'ef2e1a2bd772'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('waste_types', sa.Column('code', sa.Integer(), nullable=True))
    op.drop_column('waste_types', 'recycling_code')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('waste_types', sa.Column('recycling_code', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('waste_types', 'code')
    # ### end Alembic commands ###
